export interface TutorialStep {
  id: string;
  section: string;
  role: "admin" | "user";
  message: string;
  target: string | null;

  x?: number;
  y?: number;
  zIndex?: number;
}

export const tutorialSteps: TutorialStep[] = [
  /* ----------------------------- WELCOME ----------------------------- */
  {
    id: "welcome-1",
    section: "welcome",
    role: "admin",
    message: "Welcome to PermitPapers.com! Follow the tutorial steps to learn how the system works.",
    target: null,
    x: 700,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "welcome-1",
    section: "welcome",
    role: "user",
    message: "Welcome to PermitPapers.com! Follow the tutorial steps to learn how the system works.",
    target: null,
    x: 700,
    y: 400, 
    zIndex: 9999,
  },

  /* -------------------------- COMPANY SETUP -------------------------- */
  {
    id: "company-nav",
    section: "company-setup",
    role: "admin",
    message: "Start by clicking the 'Company' tab in the navigation bar.",
    target: "#nav-company",
    x: 820,
    y: 120,
    zIndex: 9999,
  },
  {
    id: "company-info-overview",
    section: "company-setup",
    role: "admin",
    message: "This page is used to show you the company information that will be used in your permitting paperwork. The information you type here is automatically extracted and input into the documents you will create. ",
    target: "#company-info-overview",
    x: 700,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "company-edit-btn",
    section: "company-setup",
    role: "admin",
    message: "Click 'Edit Company Info' to begin entering your company details.",
    target: "#btn-edit-company",
    x: 1280,
    y: 720, 
    zIndex: 9999,
  },
  {
    id: "company-info-section",
    section: "company-setup",
    role: "admin",
    message: "Make sure to fill out each section with all of the relevant information that you will need for your documents. The information will be input into the templates exactly how you type it here, so make sure that you are precise in what you add here.",
    target: "#company-info-section",
    x: 700,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "company-review",
    section: "company-setup",
    role: "admin",
    message: "Once you're finished inputting your company data, click 'Save Changes' to update the information.",
    target: "#company-info-overview",
    x: 1280,
    y: 720, 
    zIndex: 9999,
  },
  {
    id: "company-review",
    section: "company-setup",
    role: "admin",
    message: "It's recommended to double check the information that you typed before moving to the next step.",
    target: "#company-info-overview",
    x: 700,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "company-users-nav",
    section: "company-setup",
    role: "admin",
    message: "Once you're ready, it's time to add your employee logins. Click the 'Users' tab in the navigation to move manage your users.",
    target: "#nav-users",
    x: 820,
    y: 120, 
    zIndex: 9999,
  },

  /* -------------------------- USER MANAGEMENT ------------------------ */
  {
    id: "users-overview",
    section: "user-management",
    role: "admin",
    message: "This page will show all of the users you have signed on to your company. You can create new users and also edit existing users from this page.",
    target: "#users-overview",
    x: 700,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "users-new-btn",
    section: "user-management",
    role: "admin",
    message: "Now click 'New User' to create your first employee account.",
    target: "#btn-new-user",
    x: 1080,
    y: 160, 
    zIndex: 9999,
  },
  {
    id: "users-create-form",
    section: "user-management",
    role: "admin",
    message: "Fill out the employee's username, password, and email. You can assign a temporary password if you'd like, they can always change this for themselves later.",
    target: "#user-create-form",
    x: 700,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "users-create-submit",
    section: "user-management",
    role: "admin",
    message: "Once you have all of their information, click 'Create User' to finish.",
    target: "#btn-create-user",
    x: 560,
    y: 580, 
    zIndex: 9999,
  },

  /* ---------------------- FORMATTING PREFERENCES --------------------- */
  {
    id: "formatting-nav",
    section: "formatting",
    role: "admin",
    message: "We will now take a look at the different settings you have available in the application. Click 'Settings' when you are ready to move on to the next step.",
    target: "#tab-formatting",
    x: 970,
    y: 120, 
    zIndex: 9999,
  },
  {
    id: "formatting-nav",
    section: "formatting",
    role: "admin",
    message: "On this page you will have several tools to help you manage and personalize your application. You can adjust your personal 'User Preferences', manage your 'Subscription and Billing', as well as reach contact support should you run into any issues.",
    target: "#tab-formatting",
    x: 700,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "formatting-nav",
    section: "formatting",
    role: "admin",
    message: "For now, we will navigate to the 'Formatting Preferences' tab to finish the last step of the onboarding tutorial.",
    target: "#tab-formatting",
    x: 700,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "formatting-overview",
    section: "formatting",
    role: "admin",
    message: "These settings control how data is formatted company-wide. Making changes here will update how the customer and company information is formatted in all future documents you create.",
    target: "#formatting-overview",
    x: 700,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "formatting-save",
    section: "formatting",
    role: "admin",
    message: "Here you can decide the preferences you'd like to apply for the company. Click 'Save Formatting Preferences' after you've made your selections.",
    target: "#btn-formatting-save",
    x: 1080,
    y: 680, 
    zIndex: 9999,
  },
  {
    id: "formatting-back-dashboard",
    section: "formatting",
    role: "admin",
    message: "Once you're ready, use the 'Dashboard' button to get started with your first job.",
    target: "#nav-dashboard",
    x: 1080,
    y: 160, 
    zIndex: 9999,
  },

  /* ----------------------------- JOB FLOW ----------------------------- */
  {
    id: "job-add",
    section: "job-flow",
    role: "admin",
    message: "Click the '+ Add Job' button at the top of the table to get started.",
    target: "#btn-add-job",
    x: 700,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "job-upload",
    section: "job-flow",
    role: "admin",
    message: "The recommended workflow is to take a picture of your company's CRM and upload the image to the 'Customer Snippet' section. Alternatively, you can manually upload the customer's information to the 'Search Property Appraiser' button to automatically extract the relevant legal informatioin for the property.",
    target: "#job-upload",
    x: 700,
    y: 100, 
    zIndex: 9999,
  },
  {
    id: "job-confirm",
    section: "job-flow",
    role: "admin",
    message: "If you decided to upload a snippet, confirm that the information looks correct, you can make changes on this screen if needed. You now have the option to use this information to search the relevant Property Appraiser site to extract more information on the property, or you can simply apply this information directly to the form.",
    target: "#job-confirm",
    x: 250,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "PA-confirm",
    section: "job-flow",
    role: "admin",
    message: "You now have the option to use this information to search the relevant Property Appraiser site to extract more information on the property, or you can simply apply this information directly to the form.",
    target: "#PA-confirm",
    x: 250,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "job-confirm",
    section: "job-flow",
    role: "admin",
    message: "Click 'Run PA Search' to search the Property appraiser site. Otherwise, click 'Apply to Form' to send this information to the page.",
    target: "#job-confirm",
    x: 250,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "job-confirm",
    section: "job-flow",
    role: "admin",
    message: "If you used the 'Run PA Search' button, then you can now confirm one last time that the information looks ready to apply to the form. Edit the fields if needed, then click 'Populate Form'.",
    target: "#job-confirm",
    x: 250,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "job-missing-info",
    section: "job-flow",
    role: "admin",
    message: "Now that you have automatically filled the form with the extracted information, confirm that it looks correct. You can also add any infromation that could not be extracted like the 'Job Value' and 'Description of Improvement'.",
    target: "#job-missing-info",
    x: 700,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "job-add-doc",
    section: "job-flow",
    role: "admin",
    message: "When all of the information looks correct, you are ready to start selecting your documents. Click 'Add Document' to begin selecting the relevant documents for this job.",
    target: "#btn-add-document",
    x: 1570,
    y: 260, 
    zIndex: 9999,
  },
  {
    id: "job-doc-filters",
    section: "job-flow",
    role: "admin",
    message: "You may use the filters on this panel or simply navigate through the folder structure to select the documents needed for the county and municipality that this property resides in.",
    target: "#job-doc-filters",
    x: 700,
    y: 650, 
    zIndex: 9999,
  },
  {
    id: "job-doc-confirm",
    section: "job-flow",
    role: "admin",
    message: "You can select multiple documents at once, and apply them to this customer by clicking 'Confirm Selection'.",
    target: "#btn-doc-confirm",
    x: 1080,
    y: 650, 
    zIndex: 9999,
  },
  {
    id: "job-preview",
    section: "job-flow",
    role: "admin",
    message: "Once your documents are selected and you have all of the information needed on the form, you can select 'Save & Preview' to generate the documenets.",
    target: "#btn-save-preview",
    x: 1380,
    y: 680, 
    zIndex: 9999,
  },
  {
    id: "job-review-preview",
    section: "job-flow",
    role: "admin",
    message: "On this page, you can review the documents that you just generated. If adjustments are needed, or if there is extra information that needs to be added to the document, you can do so on this page before downloading them.",
    target: "#job-preview-screen",
    x: 700,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "job-save-doc",
    section: "job-flow",
    role: "admin",
    message: "If changes were made to the document, use the 'Save' icon in the document itself. If no changes are needed, you can also save the document by clicking the 'Open / Download' button.",
    target: "#btn-save-document",
    x: 1380,
    y: 500, 
    zIndex: 9999,
  },
  {
    id: "job-finish",
    section: "job-flow",
    role: "admin",
    message: "Once the documents are completed and downloaded, you have officially finished your first job! On this page, you can continue by starting the next, or return to the dashboard.",
    target: "#nav-dashboard",
    x: 1230,
    y: 680, 
    zIndex: 9999,
  },
  {
    id: "job-finish",
    section: "job-flow",
    role: "admin",
    message: "This concludes the tutorial! If you need to review the steps again, you can turn on specific sections in the 'Settings' tab under 'User Preferences'.",
    target: "#nav-dashboard",
    x: 700,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "job-add",
    section: "job-flow",
    role: "user",
    message: "Click the '+ Add Job' button at the top of the table to get started.",
    target: "#btn-add-job",
    x: 700,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "job-upload",
    section: "job-flow",
    role: "user",
    message: "The recommended workflow is to take a picture of your company's CRM and upload the image to the 'Customer Snippet' section. Alternatively, you can manually upload the customer's information to the 'Search Property Appraiser' button to automatically extract the relevant legal informatioin for the property.",
    target: "#job-upload",
    x: 700,
    y: 100, 
    zIndex: 9999,
  },
  {
    id: "job-confirm",
    section: "job-flow",
    role: "user",
    message: "If you decided to upload a snippet, confirm that the information looks correct, you can make changes on this screen if needed. You now have the option to use this information to search the relevant Property Appraiser site to extract more information on the property, or you can simply apply this information directly to the form.",
    target: "#job-confirm",
    x: 250,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "PA-confirm",
    section: "job-flow",
    role: "user",
    message: "You now have the option to use this information to search the relevant Property Appraiser site to extract more information on the property, or you can simply apply this information directly to the form.",
    target: "#PA-confirm",
    x: 250,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "job-confirm",
    section: "job-flow",
    role: "user",
    message: "Click 'Run PA Search' to search the Property appraiser site. Otherwise, click 'Apply to Form' to send this information to the page.",
    target: "#job-confirm",
    x: 250,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "job-confirm",
    section: "job-flow",
    role: "user",
    message: "If you used the 'Run PA Search' button, then you can now confirm one last time that the information looks ready to apply to the form. Edit the fields if needed, then click 'Populate Form'.",
    target: "#job-confirm",
    x: 250,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "job-missing-info",
    section: "job-flow",
    role: "user",
    message: "Now that you have automatically filled the form with the extracted information, confirm that it looks correct. You can also add any infromation that could not be extracted like the 'Job Value' and 'Description of Improvement'.",
    target: "#job-missing-info",
    x: 700,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "job-add-doc",
    section: "job-flow",
    role: "user",
    message: "When all of the information looks correct, you are ready to start selecting your documents. Click 'Add Document' to begin selecting the relevant documents for this job.",
    target: "#btn-add-document",
    x: 1570,
    y: 260, 
    zIndex: 9999,
  },
  {
    id: "job-doc-filters",
    section: "job-flow",
    role: "user",
    message: "You may use the filters on this panel or simply navigate through the folder structure to select the documents needed for the county and municipality that this property resides in.",
    target: "#job-doc-filters",
    x: 700,
    y: 650, 
    zIndex: 9999,
  },
  {
    id: "job-doc-confirm",
    section: "job-flow",
    role: "user",
    message: "You can select multiple documents at once, and apply them to this customer by clicking 'Confirm Selection'.",
    target: "#btn-doc-confirm",
    x: 1080,
    y: 650, 
    zIndex: 9999,
  },
  {
    id: "job-preview",
    section: "job-flow",
    role: "user",
    message: "Once your documents are selected and you have all of the information needed on the form, you can select 'Save & Preview' to generate the documenets.",
    target: "#btn-save-preview",
    x: 1380,
    y: 680, 
    zIndex: 9999,
  },
  {
    id: "job-review-preview",
    section: "job-flow",
    role: "user",
    message: "On this page, you can review the documents that you just generated. If adjustments are needed, or if there is extra information that needs to be added to the document, you can do so on this page before downloading them.",
    target: "#job-preview-screen",
    x: 700,
    y: 400, 
    zIndex: 9999,
  },
  {
    id: "job-save-doc",
    section: "job-flow",
    role: "user",
    message: "If changes were made to the document, use the 'Save' icon in the document itself. If no changes are needed, you can also save the document by clicking the 'Open / Download' button.",
    target: "#btn-save-document",
    x: 1380,
    y: 500, 
    zIndex: 9999,
  },
  {
    id: "job-finish",
    section: "job-flow",
    role: "user",
    message: "Once the documents are completed and downloaded, you have officially finished your first job! On this page, you can continue by starting the next, or return to the dashboard.",
    target: "#nav-dashboard",
    x: 1230,
    y: 680, 
    zIndex: 9999,
  },
  {
    id: "job-finish",
    section: "job-flow",
    role: "user",
    message: "This concludes the tutorial! If you need to review the steps again, you can turn on specific sections in the 'Settings' tab under 'User Preferences'.",
    target: "#nav-dashboard",
    x: 700,
    y: 400, 
    zIndex: 9999,
  },
];

/* ---------------------------------------------------------------------- */
/* ---------------------- DYNAMIC ENGINE HELPERS ------------------------ */
/* ---------------------------------------------------------------------- */

export function getStepsForSection(section: string, role: "admin" | "user") {
  return tutorialSteps.filter(s => s.section === section && s.role === role);
}

export function getStep(section: string, stepIndex: number, role: "admin" | "user") {
  const steps = getStepsForSection(section, role);
  return steps[stepIndex] ?? null;
}
